### ISSUE TITLE
[Feature] 과거에 풀었던 문제 조회

### ISSUE THREAD

**Issue by noctesilente** [Triumers/Newsnippet-Back#10]
## 과거에 풀었던 문제 조회
----------------------------------
### 이슈 목적
> 회원은 과거에 풀었던 문제를 조회할 수 있다.

### 기능 구현 내용
- [x] 사용자 ID로 과거에 풀었던 문제 조회
- [x] 문제의 카테고리, 지문, 선택지, 정답, 선택했던 답, 해설, 원본 링크, 날짜, 정답률 조회

**Comment by Leegiyeon** [comment]
문제 리스트에서 해당 문제 선택 시, 두번째 기능이 드러날 수 있도록 구현하였습니다.

- findSolvedQuizListByUserId
- findSolvedQuizByUserId
